
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const LIST_CONTACTS = 'LIST_CONTACTS';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const RESET_EDIT_ID = 'RESET_EDIT_ID';
